#!/bin/bash

# command line syntax for sander
# sander [-O] -i mdin -o mdout -p prmtop -c inpcrd -r restrt [-ref refc -x mdcrd -v mdvel -e mden -inf mdinfo]

# Run a minimization
echo "Running a minimization"

# 1) Project name
# 2) input coordinate file
# 3) output base directory
#sander -O \
#$DO_PARALLEL sander.MPI -O \
#mpirun -np 4 sander.MPI -O \

function min {
	mpirun -np 4 sander.MPI -O \
	   -i $MD_HOME/mdin/minimization.mdin \
  	   -p $MD_HOME/prmtop/$1.prmtop \
	   -c $2 \
 	   -o $3/mdout/$1.min.mdout \
	   -r $3/mdcrd/$1.min.mdcrd \
	   -e $3/mden/$1.min.mden \
	   -rdip $3/dip/$1.min.dip
}

if [ -z $1 ];
then
	echo "We need a base project name!"
	exit
else
	# we have a root name, let's check if we have a specific input filename, too
	echo "Project Name: $1"
fi

# let's see if the output dir is set
if [ -z $2 ];
then
	echo "Input coordinates: ${MD_HOME}/mdcrd/$1.mdcrd"
else
	echo "Input coordinates: $2"
fi

if [ -z $3 ];
then
	echo "Output base directory: $MD_HOME"
else
	echo "Output base directory set to $3"
fi

min $1 ${2:-${MD_HOME}/mdcrd/$1.mdcrd} ${3:-$MD_HOME};
